// Catalog snapshot from rawdre/comeketo-command-center quote.html, 2026-09-21. See docs/customer-menu.md for refresh instructions.
globalThis.PackageCatalog = {sides:[
['Rice — Mexican',0],['Rice — Plain',0],['Rice — Primavera or Pilaf',0],['Black Beans',0],['Refried Beans',0],['Garlic Mashed Potato',0],['Roasted Potatoes',0],['Glazed Sweet Potatoes',0],['Macaroni & Cheese',0],['Fried Yuca',0],['Guacamole',0],['Vegetables',0],['Bread & Butter Rolls',0],
['Loaded Garlic Mashed Potato',0.5],['Scalloped Potatoes',0.5]],mains:[
['Boneless Stuffed Chicken',0],['½ Chicken',0],['Chicken & Rice (Arroz con Pollo)',0],['Chicken Enchilada Casserole',0],['Chicken Wrapped with Bacon',0],['Chicken Piccata',0],['Chicken Marsala',0],['Chicken Alfredo or Pesto',0],['Chicken Tenders',0],['Beef or Chicken Fajitas',0],['Al Pastor Pork Medallions',0],['BBQ Pork Ribs',0],['Garlic Steak Medallions',0],['Pork Loin with Garlic Butter',0],['Italian Sausage, Peppers & Onions',0],['Tacos — Beef or Chicken',0],['Veggie Tacos',0],['Baked Ziti',0],['Cheese Ravioli',0],['Eggplant Parmesan over Penne',0],['Lasagna — Cheese',0],['Lasagna — Vegetable',0],['Lasagna — Meat (Bolognese)',0],['Stuffed Shells',0],['Beef Stroganoff over Egg Noodles',0],['Pasta Primavera',0],
['Build-Your-Own Burger Bar',0.5],['Chicken Broccoli Alfredo over Penne',1],['Chicken Cordon Bleu',1.5],['Chicken Carbonara',1.5],['Beef Short Ribs',1],['Tacos — Tinga (Chicken)',1.75],['Tacos — Birria (Beef Brisket)',2.25],['Tacos — Carnitas (Pork)',2.25],['Shrimp Tacos',2.25],['Baked Haddock',2],['Salmon',2],['Lobster Mac & Cheese',3],['Shrimp Enchiladas',3],['Shrimp with Penne Pasta',3],['Baked Stuffed Seafood',4],['Carne Asada Steak Tips',6.5],['Filet Mignon Medallions',10]],salads:[['Garden Salad',0],['Caesar Salad',0],['Taco Salad',0],['Traditional Pico de Gallo',0],['Homemade Potato Salad',0],['Broccoli Salad',0],['Pasta Salad (Tri-Color)',0],['Antipasto',1],['Fresh Fruit Platter',1]],apps:[['Mini Empanadas',5.5],['Chips & Trio of Salsas',5.5],['Chicken or Beef Taquitos',5.5],['7-Layer Dip',5.5],['Bruschetta',3.25],['Buffalo Chicken Dip',3.25],['Boneless Buffalo Wings',5.5],['Jalapeño Poppers',5.5],['Mozzarella Sticks',4.9],['Italian Meatballs',5.5],['Swedish Meatballs',5.5],['Italian Sausage (Mild)',5.5],['Spanakopita Cups',5.5],['Stuffed Mushrooms',5.5],['Spinach & Artichoke Dip with Pita',5.5],['Hummus Dip with Pita Chips',4.5],['Cheese & Cracker Platter',4.5],['Cold Vegetable Platter (Crudité)',4.5],['Garlic Shrimp',7],['Shrimp Cocktail',7],['Crab Cakes',7],['Scallops Wrapped in Bacon',8]],boards:[['Cheese & Cracker Platter',4.5],['Cold Vegetable Platter (Crudité)',4.5],['Fresh Fruit Platter',6],['Deli Platter',6.5],['Antipasto Platter',6]],styles:{
  'Buffet':      {staff:3, tiers:[['Mini',23.90,1,2],['Full',29.90,2,3],['Deluxe',35.90,3,3]]},
  'Family Style':{staff:10,tiers:[['Mini',28.90,1,2],['Full',35.90,2,4],['Deluxe',41.90,3,6]]},
  'Plated':      {staff:15,tiers:[['Mini',28.90,1,2],['Full',35.90,2,3],['Deluxe',41.90,3,3]]},
  'Drop-Off':    {staff:0, tiers:[['Mini',23.90,1,2],['Full',29.90,2,3],['Deluxe',35.90,3,3]]},
}};